#!/bin/bash

# Copyright 2017 KeyboardFire <andy@keyboardfire.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $# -ne 1 ]
then
    echo >&2 give file pls
    exit 1
fi

source "$HOME/.privim"
base="$(dirname "$(realpath "$0")")"

key="$key" file="$1" nvim="$base/neovim/build/bin/nvim" rotate="$rotate" VIM="$VIM" xterm -e "$base/privim_xterm"
