#!/usr/bin/env bash

# Copyright 2017 KeyboardFire <andy@keyboardfire.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

shopt -s extglob
echo -ne '\e[1004h'

. "$HOME/.privim"
if [ -z "$nvimflags" ]
then
    # extremely ugly hack
    nvimflags=(+)
fi

if [ -f "$file" ]
then
    gpg -r "$key" -o /dev/shm/privim -d "$file" || exit 1
fi

VIM="$VIM" "$nvim" \
    "+set noswapfile noundofile viminfo= updatetime=${idletime:-10000}" \
    +"$([ -n "$idletime" ] && echo 'aug privim|au FocusLost,CursorHold,CursorHoldI * wq|aug END')" \
    "${nvimflags[@]}" \
    /dev/shm/privim

if [ -n "$rotate" -a -f "$file" ]
then
    ls "$file".*([0-9]) | sort -Vr | while read f
    do
        bn="$(basename "$f")"
        mv "$f" "$file.$((${bn##*.}+1))"
    done
    mv "$file" "$file.0"
fi

gpg -r "$key" -o "$file" -e /dev/shm/privim

rm /dev/shm/privim
if [ -n "$killgpg" ]
then
    pgrep gpg-agent && killall -s HUP gpg-agent
fi
