#!/bin/bash

# Copyright 2017 KeyboardFire <andy@keyboardfire.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo -ne '\e[1004h'

if [ -f "$file" ]
then
    gpg -r "$key" -o /dev/shm/privim -d "$file" || exit 1
fi

"$nvim" \
    '+set noswapfile viminfo= updatetime=10000' \
    '+au FocusLost,CursorHold,CursorHoldI * wq' \
    -u NONE \
    /dev/shm/privim

if [ -f "$file" ]
then
    shopt -s extglob
    for f in "$file".*([0-9])
    do
        bn="$(basename "$f")"
        mv "$f" "$file.$((${bn##*.}+1))"
    done
    mv "$file" "$file.0"
fi

gpg -r "$key" -o "$file" -e /dev/shm/privim

rm /dev/shm/privim
pgrep gpg-agent && killall -s HUP gpg-agent
